services:
  db:
    image: mariadb:10.11.15
    container_name: esuccess_db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: esuh2918_db_success
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: esuccess_pma
    links:
      - db
    ports:
      - "8080:80" 
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 500M      # <--- Tambah ini (Batas upload 500MB)
      MEMORY_LIMIT: 512M      # <--- Tambah ini (Batas memory)
      MAX_EXECUTION_TIME: 600 # <--- Tambah ini (Waktu tunggu 10 menit)

volumes:
  mysql_data: